apiVersion: v1
kind: Build
metadata:
  name: teo-1
  namespace: teo
  selfLink: /oapi/v1/namespaces/teo/builds/teo-1
  uid: d5e55d5b-1876-11e7-b250-b6a8168af9f2
  resourceVersion: '11831'
  creationTimestamp: '2017-04-03T14:07:13Z'
  labels:
    app: teo
    buildconfig: teo
    openshift.io/build-config.name: teo
    openshift.io/build.start-policy: Serial
  annotations:
    openshift.io/build-config.name: teo
    openshift.io/build.number: '1'
    openshift.io/build.pod-name: teo-1-build
spec:
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/jmnohales/teo.git'
  revision:
    type: Git
    git:
      commit: ab23134f2c3ec607e194d976d8a1b72a7f8211e5
      author:
        name: jmnohales
        email: jmnohales@gmail.com
      committer:
        name: GitHub
        email: noreply@github.com
      message: Update README.md
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: >-
          sameersbn/redmine@sha256:2efbe7f288c8efa6a6e29cbecf56a06e577bd3c6737ae9cda4bdc598b499c52b
  output:
    to:
      kind: ImageStreamTag
      name: 'teo:latest'
    pushSecret:
      name: builder-dockercfg-r0ac1
  resources: {}
  postCommit: {}
  nodeSelector: null
  triggeredBy:
    - message: Image change
      imageChangeBuild:
        imageID: >-
          sameersbn/redmine@sha256:2efbe7f288c8efa6a6e29cbecf56a06e577bd3c6737ae9cda4bdc598b499c52b
        fromRef:
          kind: ImageStreamTag
          name: 'redmine:3.1.1-3'
status:
  phase: Complete
  startTimestamp: '2017-04-03T14:07:18Z'
  completionTimestamp: '2017-04-03T14:10:58Z'
  duration: 220000000000
  config:
    kind: BuildConfig
    namespace: teo
    name: teo
