apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: teo
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 2
    labels:
      app: teo
    name: teo
  spec:
    replicas: 1
    selector:
      app: teo
      deploymentconfig: teo
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: teo
          deploymentconfig: teo
      spec:
        containers:
        - env:
          - name: DB_TYPE
            value: postgres
          - name: DB_ADAPTER
            value: postgresql
          - name: DB_HOST
            value: postgreteo
          - name: DB_NAME
            value: redmine_production
          - name: DB_USER
            value: redmine
          - name: DB_PASS
            value: password
          image: 172.30.1.1:5000/teo/teo@sha256:29cdade6b9ff5ea1d01cf7b2d02e84e94ff57192492bf60def90b643b1b80e2d
          imagePullPolicy: Always
          name: teo
          ports:
          - containerPort: 22
            protocol: TCP
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /home/redmine/data
            name: teo-1
          - mountPath: /var/log/redmine
            name: teo-2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: teo-1
        - emptyDir: {}
          name: teo-2
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - teo
        from:
          kind: ImageStreamTag
          name: teo:latest
          namespace: teo
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: teo
    name: teo
  spec:
    ports:
    - name: 22-tcp
      port: 22
      protocol: TCP
      targetPort: 22
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      deploymentconfig: teo
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: teo
    name: teo
  spec:
    host: teo-teo.192.168.42.36.xip.io
    port:
      targetPort: 80-tcp
    to:
      kind: Service
      name: teo
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2017-04-05T10:20:21Z
        status: "True"
        type: Admitted
      host: teo-teo.192.168.42.36.xip.io
      routerName: router
